const BAD_REQUEST = 400;

const DEFAULT_DEBOUNCE_TIME_MS = 300;

const DEFAULT_DEDUPE_INTERVAL = 10 * 60 * 1000;

const DEFAULT_ERROR_RETRIES = 3;

const DEFAULT_ERROR_RETRY_INTERVAL = 60 * 1000;

const DEFAULT_EXTERNAL_IMAGE_HEIGHT = 400;

const DEFAULT_EXTERNAL_IMAGE_WIDTH = 400;

const DEFAULT_MAX_CART_GROCERIES = 1000;

const DEFAULT_PAGE_SIZE = 20;

const DEFAULT_REFRESH_INTERVAL = 10 * 60 * 1000;

const FORM_REQUIRED_FEILD_ERROR = 'Field required';

const ROUTES = {
    apiCartGroceries: '/api/cartGroceries',
    apiCarts: '/api/carts',
    apiGroceries: '/api/groceries',
    carts: '/carts',
    groceries: '/groceries',
};

export {
    BAD_REQUEST,
    DEFAULT_DEBOUNCE_TIME_MS,
    DEFAULT_DEDUPE_INTERVAL,
    DEFAULT_ERROR_RETRIES,
    DEFAULT_ERROR_RETRY_INTERVAL,
    DEFAULT_EXTERNAL_IMAGE_HEIGHT,
    DEFAULT_EXTERNAL_IMAGE_WIDTH,
    DEFAULT_MAX_CART_GROCERIES,
    DEFAULT_PAGE_SIZE,
    DEFAULT_REFRESH_INTERVAL,
    FORM_REQUIRED_FEILD_ERROR,
    ROUTES,
};
