const BAD_REQUEST = 400;

const DEFAULT_PAGE_SIZE = 20;

const DEFAULT_EXTERNAL_IMAGE_WIDTH = 400;

const DEFAULT_EXTERNAL_IMAGE_HEIGHT = 400;

export {
    BAD_REQUEST,
    DEFAULT_EXTERNAL_IMAGE_HEIGHT,
    DEFAULT_EXTERNAL_IMAGE_WIDTH,
    DEFAULT_PAGE_SIZE,
};
