const BAD_REQUEST = 400;

const DEFAULT_PAGE_SIZE = 20;

const DEFAULT_EXTERNAL_IMAGE_WIDTH = 400;

const DEFAULT_EXTERNAL_IMAGE_HEIGHT = 400;

const DEFAULT_MAX_CART_GROCERIES = 1000;

const FORM_REQUIRED_FEILD_ERROR = 'Field required';

export {
    BAD_REQUEST,
    DEFAULT_EXTERNAL_IMAGE_HEIGHT,
    DEFAULT_EXTERNAL_IMAGE_WIDTH,
    DEFAULT_MAX_CART_GROCERIES,
    DEFAULT_PAGE_SIZE,
    FORM_REQUIRED_FEILD_ERROR,
};
